baseurl: /
theme: jekyll-theme-midnight

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme info.
title: PHPCSDevTools
description: "A set of tools to assist developers of sniffs for PHP CodeSniffer."
show_downloads: false
google_analytics:

# SEO info.
tagline: "A set of tools to assist developers of sniffs for PHP CodeSniffer."
twitter:
  username: jrf_nl
  card: summary
  hashtags: PHPCSDevTools
author:
  twitter: jrf_nl

# Files to exclude when generating the site.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - artifacts/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CNAME
  - README.md
  - .jekyll-metadata
  - .gitignore
  - .github
  - '*.bak'
  - '*.orig'
